/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneType } from './phone-type';


export interface CreatePhoneNumberRequest { 
    type?: PhoneType;
    number: string;
}
export namespace CreatePhoneNumberRequest {
}


