/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceStatus } from './attendance-status';


export interface CreateTrainingParticipantRequest { 
    trainingId: string;
    personId: string;
    attendanceStatus: AttendanceStatus;
    notes?: string;
}



