/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrainingStatus } from './training-status';


export interface CreateTrainingRequest { 
    teamId: string;
    trainingDate: string;
    startTime?: string;
    endTime?: string;
    location?: string;
    notes?: string;
    status?: TrainingStatus;
}
export namespace CreateTrainingRequest {
}


