/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamMemberRole } from './team-member-role';


export interface CreateTeamMembershipRequest { 
    teamId: string;
    personId: string;
    role: TeamMemberRole;
    joinedAt?: string;
    leftAt?: string;
}



