/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RelationType } from './relation-type';


export interface CreatePersonRelationRequest { 
    childPersonId?: string;
    guardianPersonId?: string;
    relationType?: RelationType;
}
export namespace CreatePersonRelationRequest {
}


