/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PersonDto } from './person-dto';
import { RelationType } from './relation-type';


export interface PersonRelationDto { 
    id?: string;
    childPerson?: PersonDto;
    guardianPerson?: PersonDto;
    relationType?: RelationType;
}
export namespace PersonRelationDto {
}


