/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneType } from './phone-type';


export interface PhoneNumberDto { 
    id?: string;
    type?: PhoneType;
    number?: string;
}
export namespace PhoneNumberDto {
}


