/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum PhoneType {

    Mobile = 'MOBILE',

    Home = 'HOME',

    Work = 'WORK',

    Emergency = 'EMERGENCY'
}

