/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PhoneType = {
    Mobile: 'MOBILE',
    Home: 'HOME',
    Work: 'WORK',
    Emergency: 'EMERGENCY'
} as const;
export type PhoneType = typeof PhoneType[keyof typeof PhoneType];

