/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum RelationType {

    Mother = 'MOTHER',

    Father = 'FATHER',

    Grandmother = 'GRANDMOTHER',

    Grandfather = 'GRANDFATHER',

    StepParent = 'STEP_PARENT',

    Other = 'OTHER'
}

