/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const TeamMemberRole = {
    Player: 'PLAYER',
    Coach: 'COACH',
    AssistantCoach: 'ASSISTANT_COACH'
} as const;
export type TeamMemberRole = typeof TeamMemberRole[keyof typeof TeamMemberRole];

