/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceStatus } from './attendance-status';
import { TrainingDto } from './training-dto';
import { PersonDto } from './person-dto';


export interface TrainingParticipantDto { 
    id?: string;
    training?: TrainingDto;
    person?: PersonDto;
    attendanceStatus?: AttendanceStatus;
    notes?: string;
    createdAt?: string;
    updatedAt?: string;
}



