/**
 * Coach Buddy API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamDto } from './team-dto';
import { TrainingStatus } from './training-status';


export interface TrainingDto { 
    id?: string;
    team?: TeamDto;
    trainingDate?: string;
    startTime?: string;
    endTime?: string;
    location?: string;
    notes?: string;
    status?: TrainingStatus;
    createdAt?: string;
    updatedAt?: string;
}



