export * from './auth.service';
import { AuthService } from './auth.service';
export * from './person-relations.service';
import { PersonRelationsService } from './person-relations.service';
export * from './persons.service';
import { PersonsService } from './persons.service';
export * from './seasons.service';
import { SeasonsService } from './seasons.service';
export * from './team-memberships.service';
import { TeamMembershipsService } from './team-memberships.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './training-participants.service';
import { TrainingParticipantsService } from './training-participants.service';
export * from './trainings.service';
import { TrainingsService } from './trainings.service';
export const APIS = [AuthService, PersonRelationsService, PersonsService, SeasonsService, TeamMembershipsService, TeamsService, TrainingParticipantsService, TrainingsService];
