quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=coach_buddy
quarkus.datasource.password=coach_buddy
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/coach_buddy

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.database.default-schema=coach_buddy

quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=coach_buddy
quarkus.flyway.default-schema=coach_buddy

quarkus.smallrye-openapi.info-title=Coach Buddy API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API für Trainings-, Team- und Personenverwaltung